# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-23 04:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagenplanta',
            name='foto',
            field=models.FileField(upload_to='imagenes_plantas'),
        ),
    ]
